datasource:
  type: apisports
  poll_interval_seconds: 360
feishu:
  webhook_url: https://open.feishu.cn/open-apis/bot/v2/hook/0f9390fa-9079-4556-bffd-ca85c09de287
apisports:
  keys:
  - d5934d8a5fe79046aa6b8e892927fcfe
# MiniMax 翻译 API: https://platform.minimaxi.com 获取 key
minimax:
  api_url: "https://api.minimax.chat/v1/text/chatcompletion_v2"
  key: ""
juhe_api:
  key: ''
