datasource:
  type: apisports
  poll_interval_seconds: 300
feishu:
  webhook_url: https://open.feishu.cn/open-apis/bot/v2/hook/0f9390fa-9079-4556-bffd-ca85c09de287
apisports:
  keys:
  - 2a12a938912687cb44e0f6d60d679c11
minimax:
  api_url: https://api.minimax.chat/v1/text/chatcompletion_v2
  keys:
    - eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJHcm91cE5hbWUiOiJ6aG91IiwiVXNlck5hbWUiOiJ6aG91IiwiQWNjb3VudCI6IiIsIlN1YmplY3RJRCI6IjE5ODg4Nzc2NDE1NDkwOTA5MTEiLCJQaG9uZSI6IjEzMTk3ODcyOTg2IiwiR3JvdXBJRCI6IjE5ODg4Nzc2NDE1NDA3MDIzMDMiLCJQYWdlTmFtZSI6IiIsIk1haWwiOiIiLCJDcmVhdGVUaW1lIjoiMjAyNS0xMi0xMiAxMDoyNTozNCIsIlRva2VuVHlwZSI6NCwiaXNzIjoibWluaW1heCJ9.kFRTC_MB_eLsgrrKxB_-aBYhR00NPgE4_ZEJcTHusN84arK_pCURGmvfLJjNXJS_XuEcbbYX6rS8gMF0m500uhqZDoXgGnV6mMPRZpz0ZK4DLVmpqrmL3ICG3Wkv44QPbI_66-M_2pCE3ulB9QxqiIGOuVtIzRR1hudlDs-lNRFklM2CSsJMdP4kZ-1RSmk70KEb4okGFD_h9FOQfucTBCQn_foZNb1z9e1NvbwN-wnAI3zQv6MCOY7eJQ33nVUcDWB7Z4jJAh8OeUKLKx4mtYVNIsJ4OJJcntQJ46Bs3qL05hqfL8nQpJnqH3_vOTyzm5GZleAZ58tDNy7XgFPJ4g
    # - "第二个key"
isports:
  api_url: "http://api.isportsapi.com"   # 或 http://api-asia.isportsapi.com（亚洲优化）
  key: ""                                # 填你的 iSports API key

thesportsdb:
  key: "3"

juhe_api:
  key: ''
